# Generated by Django 5.0.7 on 2024-08-03 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=16)),
                ('about', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
